<?php
	//define('DBhost','ashram777.cafe24.com');
    //define('DBuser','ashram777');
    //define('DBpass','dhanstjd77!');
    //define('DBname','ashram777');
    define('DBhost','localhost');
    define('DBuser','ajy6712');
    define('DBpass','ay2111!!');
    define('DBname','ajy6712');
?>